### ISSUE TITLE
NPE in SelectorBuilder for CMMN tasks

### ISSUE THREAD

**Issue by malteser** [camunda/camunda-bpm-reactor#19]
````
Caused by: java.lang.NullPointerException
	at org.camunda.bpm.extension.reactor.SelectorBuilder.extractTypeName(SelectorBuilder.java:138) ~[camunda-bpm-reactor-core-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
	at org.camunda.bpm.extension.reactor.SelectorBuilder.selector(SelectorBuilder.java:26) ~[camunda-bpm-reactor-core-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
	at org.camunda.bpm.extension.reactor.listener.PublisherTaskListener.notify(PublisherTaskListener.java:20) ~[camunda-bpm-reactor-core-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
````

When using the SelectorBuilder with a DelegateTask, the builder is not aware of the CMMNness of the task and will therefore cast the DelegateTask to BpmnModelExecutionContext which - fo course - it is not.

**Comment by malteser** [comment]
will fix this while provoding a CMMN example

**Comment by malteser** [comment]
BTW TaskEntity implements BpmnModelExecutionContext. This is misleading as the TaskEntity might represent a case task, too.

**Comment by jangalinski** [comment]
See also: https://app.camunda.com/jira/browse/CAM-5371
